### ISSUE TITLE
1.18.2 Fabric: Not Remembering created worlds,

### ISSUE THREAD

**Issue by Merith-TK** [IsaiahMC/multiworld#18]
The mod is not remembering created worlds at all, 

i created an world called build last night before I logged off, and
![image](https://user-images.githubusercontent.com/10422110/176926296-1f68b0ef-fcc0-4ffe-bf24-da7b28832045.png)

https://git.merith.xyz/modpacks/ultron/src/branch/server < the mods on the server

**Comment by SeppDE** [comment]
Can confirm. The server isn't loading the created worlds after a restart of Client (Singleplayer) or server (Multiplayer)

**Comment by dAKirby309** [comment]
Yes this is definitely still an issue, even on 1.19, server and single player. Is there at least a way to make a command block automatically send command "mw create <same name as existing world> [type of world]" as soon as the world starts up?
