### ISSUE TITLE
Server console errors out when trying to create a world (Fabric: 1.19)

### ISSUE THREAD

**Issue by MrRagtime** [IsaiahMC/multiworld#19]
![image](https://user-images.githubusercontent.com/65317484/178158894-5401f67b-7b05-4c36-991d-c66de1719ca7.png)

**Comment by wackoamd1** [comment]
don't worry about it , the shit just doesnt work.
be happy u even watched the console else u would be stuck when u would have tried to tp to your new world.
kicked from server and no way to get back on
i made a comment about it yesterday and thats now mysteriously vanished

**Comment by MrRagtime** [comment]
other people are having the issues with this mod as well.
For example, issue https://github.com/IsaiahMC/multiworld/issues/18 is having problems with the mod not rendering anything at all. Which is also something I'm having issues with but they're using 1.18 and I'm using 1.19.
So it seems like no matter what version you download, it just won't work.

**Comment by IsaiahPatton** [comment]
It's currently a player-only command.

**Comment by MrRagtime** [comment]
@IsaiahPatton I've already "/mw create" in-game. nothing changes and I still get errors in my server console.

**Comment by IsaiahPatton** [comment]
what is the error during ingame?

**Comment by MrRagtime** [comment]
Legit, nothing.
No message at all.

**Comment by MrRagtime** [comment]
### **I assume this bug won't be fixed for awhile.**
