### ISSUE TITLE
Can't run command on server consoles

### ISSUE THREAD

**Issue by Breswii** [IsaiahMC/multiworld#59]
i try to run a tp command on server consoles，but it didn't works,show me error as follow:
`[Server thread/INFO]: [STDERR]: com.mojang.brigadier.exceptions.CommandSyntaxException: A player is required to run this command here`
i want to know how to make it works on server consoles?

**Comment by Foxtrek64** [comment]
Hopefully I can provide some context as to why this isn't working. The TP command moves the player who ran the command to the specified world. While the "console" user is capable of executing commands, they are not a player and do not exist in the world, so they cannot be moved to any world.

I could see the inclusion of a command to move a targeted player to the specified world, perhaps as an overload of the existing command. This would be allowed to be run from the console as the player to move changes from the command executor to the player specified. To be clear, this command **does not exist**.
```
/mw tp Notch minecraft:nether
```
