### ISSUE TITLE
mod is listed as loading at startup with fabric - but commands do not work, even as op?

### ISSUE THREAD

**Issue by gleep52** [IsaiahMC/multiworld#65]
I have the latest vanilla 1.20.6 MC installed - latest fabric installer 1.0.1 - latest version of fabric mod in my mod folder - the startup says the following modes are loading:
fabricloader 0.15.11
\-- mixinextras 0.3.5
java 22
minecraft 1.20.6
multiworld-bundle bundle

However it does specify the line right above that before it loads:
[ForkJoinPool-1-worker-2/WARN]: Mod multiworld-bundle uses the version bundle which isn't compatible with Loader's extended semantic version format (Could not parse version number component 'bundle'!), SemVer is recommended for reliably evaluating dependencies and prioritizing newer version

How can I properly identify the bundle for fabric to work with this mod?

**Comment by pisaiah** [comment]
could you provide the full log file?

**Comment by gleep52** [comment]
Yep - i was missing fabric-api.  Thank you!
