### ISSUE TITLE
1.18.2 Support

### ISSUE THREAD

**Issue by LucaSchwan** [IsaiahMC/multiworld#8]
Feature Request:
Could you maybe update this Mod for Minecraft version 1.18.2. I've seen it is currently for 1.18.1 and that hopefully shouldn't be too much.

**Comment by axiades** [comment]
Please Update to 1.18.2

**Comment by SpigotDE** [comment]
Oh yes 1.18.2 - we need you

**Comment by IsaiahPatton** [comment]
Try this version: [Multiworld-Fabric-1.4.jar](https://cdn.modrinth.com/data/fgvoNDL1/versions/1.4/Multiworld-Fabric-1.4.jar)

**Comment by SpigotDE** [comment]
Thanks for the fast fix , btw is it possible to get the Terralith worldgen ( its a datapack ) 

https://www.curseforge.com/minecraft/mc-mods/terralith
